### PR TITLE
Queues using linked list            Add files via upload

### PR DESCRIPTION
**Pull request by Amritapandey22**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed # (issue) (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Data Structure 
- [ ] New Algorithm

# Checklist:

- [ ] I have squashed my commits
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My code is a working bug-free code

### CODE REVIEW

**Comment by Amritapandey22** [comment]
Queues implemented using linked list in c++

**Review by Manvityagi — CHANGES_REQUESTED** [review]
@Amritapandey22  

@Amritapandey22 
- You should first create an issue for the code you are adding, 
- Add only 1 code in 1 PR 
- So, open 4 issues corresponding to the 4 codes you want to add 
- Send 1 PR for 1 code 
- DOCUMENTATION.md must be updated accordingly

**Review by Manvityagi — CHANGES_REQUESTED** [review]
None of the requested changes are present here @Amritapandey22

**Comment by Amritapandey22** [comment]
I am sorry to trouble you but I created the issue and also made a PR
regarding it ,mentioning the issue.

**Comment by ay2306** [comment]
You have uploaded more files than required. You are assigned to write code for implementing a queue using a linked list. You do not need to upload other files please delete them. Upload one file which we can review. 

Thank you.

**Pull request closed without merging**
